---
stages:
  - release
  
release_to_github:
  stage: release
  image: alpine:3.6
  environment: production

  rules :
    - if: '$CI_COMMIT_BRANCH =~ /\Amaster\z/'
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH =~ /\Amaster\z/' 
      when: always
    - when: never

  variables:
    GIT_DEPTH: 1000
    DOCS_PROSTORE_ARCHIVE_PUBLIC_REPO_URL: git@github.com:bronekalmar/docs_prostore_archive.git

  before_script:
    - apk add --no-cache bash git openssh-client
    - cat $git_push_to_github > /usr/local/bin/git-push
    - chmod +x /usr/local/bin/git-push
    - CI_SSH_KEY=SSH_PRIVATE_KEY_$(echo ${CI_PROJECT_NAME} | tr '-' '_' | tr '[:upper:]' '[:lower:]')
    - export SSH_PRIVATE_KEY=$(eval "echo \"\$${CI_SSH_KEY}\"")
    
  script: 
    - git-push ${DOCS_PROSTORE_ARCHIVE_PUBLIC_REPO_URL}
