---
stages:
  - release
  
release_to_github:
  stage: release
  image: alpine:3.6
  environment: production

  rules :
    - when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /\Aci\z/'
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH =~ /\Aci\z/' 
      when: always
    - when: never

  variables:
    # Prevent "shallow update not allowed" error.
    # Set it to maximum possible count of *new* commits that you foresee being pushed to a remote.
    GIT_DEPTH: 1000

  before_script:
    - apk add --no-cache bash git openssh-client
    - cat $git_push_to_github > /usr/local/bin/git-push
    - chmod +x /usr/local/bin/git-push
    - CI_SSH_KEY=SSH_PRIVATE_KEY_$(echo ${CI_PROJECT_NAME} | tr '-' '_' | tr '[:upper:]' '[:lower:]')
    - export SSH_PRIVATE_KEY=$(eval "echo \"\$${CI_SSH_KEY}\"")
    
  script: 
    - git-push git@github.com:bronekalmar/docs_prostore_archive.git
